f = figure;

set(f,'Tag','covDataGUI','HandleVisibility','on');

uicontrol('Style','text','units','normalized','position',[0.125 .85 .75 .1],...
    'string','Input Covariance Data','FontSize',28);

uicontrol('Style','text','units','normalized','position',[1/12 .7 1/3 .08],...
    'string','Position [m^2]','FontSize',20);

uicontrol('Style','text','units','normalized','position',[7/12 .7 1/3 .08],...
    'string','Velocity [m^2/s]','FontSize',20);

varxx_h = uicontrol('style','edit','units','normalized',...
    'position',[.04 .55 1/8 .08]);

covxy_h = uicontrol('style','edit','units','normalized',...
    'position',[.195 .55 1/8 .08]);

covxz_h = uicontrol('style','edit','units','normalized',...
    'position',[.34 .55 1/8 .08]);

covyz_h = uicontrol('style','edit','units','normalized',...
    'position',[.34 .45 1/8 .08]);

varyy_h = uicontrol('style','edit','units','normalized',...
    'position',[.195 .45 1/8 .08]);

varzz_h = uicontrol('style','edit','units','normalized',...
    'position',[.34 .35 1/8 .08]);

varVxx_h = uicontrol('style','edit','units','normalized',...
    'position',[.535 .55 1/8 .08]);

covVxy_h = uicontrol('style','edit','units','normalized',...
    'position',[.68 .55 1/8 .08]);

covVxz_h = uicontrol('style','edit','units','normalized',...
    'position',[.825 .55 1/8 .08]);

covVyz_h = uicontrol('style','edit','units','normalized',...
    'position',[.825 .45 1/8 .08]);

varVyy_h = uicontrol('style','edit','units','normalized',...
    'position',[.68 .45 1/8 .08]);

varVzz_h = uicontrol('style','edit','units','normalized',...
    'position',[.825 .35 1/8 .08]);

but_h = uicontrol('style','pushbutton','string','Input Values','units',...
    'normalized','position',[.05 .1 .4 .15],'callback',...
    {@input_values1,f,varxx_h,varyy_h,varzz_h,covxy_h,covxz_h,covyz_h,...
    varVxx_h,varVyy_h,varVzz_h,covVxy_h,covVxz_h,covVyz_h});

resume_but_h = uicontrol('style','pushbutton','string','Resume Script',...
    'units','normalized','position',[.55 .1 .4 .15],...
    'callback','uiresume(f)');